version: '3'
services:
  db:
    container_name: internet_tv_mysql
    image: mysql:8.0.33
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    ports:
      - 3306:3306
    env_file:
      - ./.env
    volumes:
      - ./data:/var/lib/mysql
      - .:/Internet_TV